version: '3.8'

services:
  db:
    image: postgres
    container_name: inventory-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory   # ✅ Let Docker create it
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
