services:
  postgres:
    image: postgres
    container_name: postgres_inventory
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: lokesh220/fi-assignment-app:latest  
    container_name: go_inventory_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
